### ISSUE TITLE
Negative value in mozlint tasks crashes the bot

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#265]
See https://firefoxci.taskcluster-artifacts.net/Zs4uj7w6Q3ylEuC4fPhhgA/0/public/logs/live_backing.log

**Comment by marco-c** [comment]
So I guess #175 was not complete?

**Comment by marco-c** [comment]
It's strange because we are supposed to convert -1 to None at https://github.com/mozilla/code-review/blob/210d0109e7764b52feae1bd9655b4b313bd6baad/bot/code_review_bot/__init__.py#L73, and then contains should return early when line is None: https://github.com/mozilla/code-review/blob/210d0109e7764b52feae1bd9655b4b313bd6baad/bot/code_review_bot/revisions.py#L222.

**Comment by La0** [comment]
We are just not running the recent code in prod.
Doing a release now seems like a really good idea...

**Comment by marco-c** [comment]
Aaaah, that explains everything :P

**Comment by La0** [comment]
We should be good now that 1.0.7 has landed

**Comment by marco-c** [comment]
So we can close as duplicate of #168.

**Comment by La0** [comment]
I tested locally with current master, seems to work fine
