### ISSUE TITLE
Investigate lint-related backouts

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#360]
We still have quite a few backouts due to linting issues. We should investigate them and figure out why the bot didn't prevent them.

**Comment by marco-c** [comment]
See also #359, there are a couple of examples. Joel is going to give me a longer list soon.

**Comment by marco-c** [comment]
Here's a list of recent backouts due to linting issues:
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=08056399677f857d6f2b8189532cb28cde666a81
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=dcab270db63af6dfb9ab0e3740c06866c49cb993
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=90cf0ce6c916dc56b5b5c0577f468fc5c4e89745
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=196d61adc272d60474f16604af64f1b34bcb4098
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=bd27dfd96896dde5f30d6d3942072cf35fba7827 (decision task)
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=a37d83819f44c542699e5069b4609b47584b2c9e
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=096660d5d8b6834c035032d7f82905ebc4592c12
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=020fa463a54c9d10dc625cd68347b68dcb907baf
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=617f7b891207ba317cdacbe3ee0c0d943ddc2c1c (decision task)
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=fa933e86341b673bb82b05805e7f59974b731b68
- [ ] https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=6310de06db5f3a6934d1831d5a028c761355f86d

Let's mark the ones which we analyze and for which we have an issue on file which would cover them.

**Comment by La0** [comment]
[We saw the issue on Bug 1601708 initially](https://code-review.moz.tools/#/?search=1601708%20) but did not report it because of not in patch.

This is a good example that we can track a backout in the backend now, the revision went from try to autoland, back to try to fix the lint issue, then again on autoland.

**Comment by La0** [comment]
[Bug 1601612](https://code-review.moz.tools/#/?search=1601612) from @sylvestre got no issues detected at all until it reached autoland (then the 14 issues from the backout were listed by the bot).

I think no issue was reported because [the files impacted](https://phabricator.services.mozilla.com/D57509) were not in patch at all: no pycompat task was triggered on those files before reaching autoland (as we run on --outgoing).

I'm not sure we can fix this without incurring a big performance penalty ?

**Comment by La0** [comment]
Bug 1603461 failed [for 2 eslint issues](https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=f911e3de6e53869f12165dd95b6ac095cd919330&selectedJob=281441263): these 2 issues were detected & [reported by the bot](https://phabricator.services.mozilla.com/D56954#1734712) [several](https://phabricator.services.mozilla.com/D56954#1738855) [times](https://phabricator.services.mozilla.com/D56954#1745504) but the patch was sent to autoland anyway.
When [the dev fixed the issue](https://phabricator.services.mozilla.com/D56954#1751117), the patch landed.

I think this could be prevented with #25

**Comment by marco-c** [comment]
> I think no issue was reported because the files impacted were not in patch at all: no pycompat task was triggered on those files before reaching autoland (as we run on --outgoing).

> I'm not sure we can fix this without incurring a big performance penalty ?

Don't we run exactly the same task as autoland?

**Comment by La0** [comment]
Bug 1603300 failed for [2 lines too long in some python code](https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=5b1c7a3bd4b2d73cd99fd2ea29b7200f6385bee1&selectedJob=280781691)

We [detected & reported them twice](https://phabricator.services.mozilla.com/D56828#1731068), the landing failed, the [dev fixed it](https://phabricator.services.mozilla.com/D56828?id=206479), it landed.

I think this could be prevented with #25

**Comment by marco-c** [comment]
For the cases where the devs ignored them, maybe we should contact them and ask them why, so we can plan for the best UI for #25 (even though most likely the best UI would be the warning in Lando).

**Comment by La0** [comment]
Bug 1601093 failed [with 2 eslint errors](https://treeherder.mozilla.org/#/jobs?repo=autoland&selectedJob=280708546&resultStatus=testfailed%2Cbusted%2Cexception&revision=dd809e835f2a8f2c6a1c5269d08b0b90e048c317).
[They were not reported because the bot failed on a bad download](https://firefox-ci-tc.services.mozilla.com/tasks/aqD79H8tQv2dfSCkrBNxpQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FaqD79H8tQv2dfSCkrBNxpQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) - this was fixed since in #321

**Comment by La0** [comment]
Bug 1587080 failed with [perdocs errors](https://treeherder.mozilla.org/#/jobs?repo=autoland&selectedJob=280503992&resultStatus=testfailed%2Cbusted%2Cexception&revision=34efe80bfd6105472a1a13731a7087856f56fa02).
The bot [detected lot of issues on that stack](https://code-review.moz.tools/#/?search=1587080) but no perfdocs [seen on the phab revision](https://phabricator.services.mozilla.com/D50227)

I think that may be a chicken/egg issue: they are adding [that check in the stack](https://phabricator.services.mozilla.com/D53647), but it did not trigger properly on try on all revs ? That stack was also made on the old & new Taskcluster instances... does not help.

The perfdocs check seem to work now as it's reporting issues [in our stats](https://code-review.moz.tools/#/stats). I'll skip this one.

**Comment by La0** [comment]
Bug 1599580 failed [for android linting issues](https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=64fd406639309a24f4307583456aa883adc8a953&selectedJob=279899132).

These issues were reported by the bot [with our anormal task failure detection](https://phabricator.services.mozilla.com/D55730#1707235) but i guess the comment was ignored.

Note: [in the mozlint failure](https://firefox-ci-tc.services.mozilla.com/tasks/Ae_wNDCjTla6A3ptPR2rhw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FAe_wNDCjTla6A3ptPR2rhw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log), the last line is `No lint issues found` which may induce some confusion... no issues were detected because it crashed !

**Comment by La0** [comment]
Bug 1603804 failed [for py-compat issues](https://treeherder.mozilla.org/#/jobs?repo=autoland&selectedJob=281942636&resultStatus=testfailed%2Cbusted%2Cexception&searchStr=lint&revision=69687a23245e28d052a71c4eb1195423554bdafb)

Those [were detected by the bot](https://firefox-ci-tc.services.mozilla.com/tasks/RsK5ERUkQRiG1rm-jq9Zcw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FRsK5ERUkQRiG1rm-jq9Zcw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L175), but not detected by the bot as not in patch.

Would be fixed by #365

**Comment by La0** [comment]
Bugs 1603452, 1603114 & 1577596 failed on the same push [on 1 android lint issue](https://treeherder.mozilla.org/#/jobs?repo=autoland&selectedJob=281640508&resultStatus=testfailed%2Cbusted%2Cexception&revision=1a9be6d049a78ad37c99298dfce43fba6dd45687)

That issue was not detected at all by the bot on all 3 revisions.
[It looks like the fix was made here](https://phabricator.services.mozilla.com/D57134?vs=209453&id=209912#change-unV5KWnwRKIr)

The line number seem to be off to be in patch though, so it should be a #365

**Comment by La0** [comment]
DD57134 is in Bug 1577596 which was in the push mentionned just above => #364

**Comment by La0** [comment]
> > I think no issue was reported because the files impacted were not in patch at all: no pycompat task was triggered on those files before reaching autoland (as we run on --outgoing).
> 
> > I'm not sure we can fix this without incurring a big performance penalty ?
> 
> Don't we run exactly the same task as autoland?

You're right, it's the same task (no outgoing on either tasks).
I still don't know why no issues were detected [at all until it reached autoland](https://code-review.moz.tools/#/?search=1601612)
